definitions:
  domain.Mapping:
    properties:
      host:
        type: string
      id:
        type: string
    type: object
  rest.Error:
    properties:
      messages:
        items:
          type: string
        type: array
      ops:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /mapping:
    get:
      consumes:
      - application/json
      description: Method to get all mappings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Mapping'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Error'
      summary: Get Mappings
      tags:
      - Mapping
  /mapping/{id}:
    get:
      consumes:
      - application/json
      description: Method to get mapping by id
      parameters:
      - description: Mapping Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Mapping'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Error'
      summary: Get Mapping by Id
      tags:
      - Mapping
swagger: "2.0"
